# Generated by Django 6.0.2 on 2026-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('jobseeker', 'JobSeeker')], max_length=20, null=True),
        ),
    ]
