# Generated by Django 6.0.2 on 2026-03-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_user_role_user_is_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Submitted', max_length=20),
        ),
    ]
