# Generated by Django 6.0.2 on 2026-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_company_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Submitted', max_length=20),
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
    ]
